"""Tool schemas exposed to the LLM."""

TOOL_SCHEMAS = [
    {"type": "function", "function": {
        "name": "remember_fact",
        "description": "Store a durable fact about the user for future sessions.",
        "parameters": {"type": "object",
                       "properties": {"fact": {"type": "string"},
                                      "category": {"type": "string"}},
                       "required": ["fact"]}}},
    {"type": "function", "function": {
        "name": "switch_mood",
        "description": "Switch JARVIS mood: instant, thinking, deep, coding, creative, tutor, fast.",
        "parameters": {"type": "object",
                       "properties": {"name": {"type": "string"}},
                       "required": ["name"]}}},
    {"type": "function", "function": {
        "name": "read_own_code",
        "description": "Read one of JARVIS own source files.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}},
                       "required": ["path"]}}},
    {"type": "function", "function": {
        "name": "deep_search",
        "description": "Research a question thoroughly across multiple web sources with citations. Slower than fast_search but more reliable.",
        "parameters": {"type": "object",
                       "properties": {"question": {"type": "string"}},
                       "required": ["question"]}}},
    {"type": "function", "function": {
        "name": "silent_browse",
        "description": "Open a URL in an INVISIBLE browser (no window).",
        "parameters": {"type": "object",
                       "properties": {"url": {"type": "string"}},
                       "required": ["url"]}}},
    {"type": "function", "function": {
        "name": "silent_search",
        "description": "Search Google in the INVISIBLE browser.",
        "parameters": {"type": "object",
                       "properties": {"query": {"type": "string"},
                                      "max_results": {"type": "integer"}},
                       "required": ["query"]}}},
    {"type": "function", "function": {
        "name": "silent_read",
        "description": "Read visible text from the invisible browser page.",
        "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {
        "name": "silent_click",
        "description": "Click a link in the invisible browser.",
        "parameters": {"type": "object",
                       "properties": {"text": {"type": "string"}},
                       "required": ["text"]}}},
    {"type": "function", "function": {
        "name": "fs_read",
        "description": "Read a file's contents.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}},
                       "required": ["path"]}}},
    {"type": "function", "function": {
        "name": "fs_write",
        "description": "Write (create/overwrite) a file. Overwrites back up first.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"},
                                      "content": {"type": "string"}},
                       "required": ["path", "content"]}}},
    {"type": "function", "function": {
        "name": "fs_append",
        "description": "Append content to a file.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"},
                                      "content": {"type": "string"}},
                       "required": ["path", "content"]}}},
    {"type": "function", "function": {
        "name": "fs_list",
        "description": "List files in a directory.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}}}}},
    {"type": "function", "function": {
        "name": "fs_search",
        "description": "Search for files by name pattern.",
        "parameters": {"type": "object",
                       "properties": {"pattern": {"type": "string"},
                                      "root": {"type": "string"}},
                       "required": ["pattern"]}}},
    {"type": "function", "function": {
        "name": "fs_delete",
        "description": "Delete a file/folder (backup saved first).",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}},
                       "required": ["path"]}}},
    {"type": "function", "function": {
        "name": "fs_mkdir",
        "description": "Create a directory.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}},
                       "required": ["path"]}}},
    {"type": "function", "function": {
        "name": "term_run",
        "description": "Run a safe shell command (git, python, pip, dir, etc.).",
        "parameters": {"type": "object",
                       "properties": {"command": {"type": "string"},
                                      "timeout": {"type": "integer"}},
                       "required": ["command"]}}},
    {"type": "function", "function": {
        "name": "term_python",
        "description": "Run inline Python code.",
        "parameters": {"type": "object",
                       "properties": {"code": {"type": "string"},
                                      "timeout": {"type": "integer"}},
                       "required": ["code"]}}},
    {"type": "function", "function": {
        "name": "list_open_apps",
        "description": "List all open windows on the user's computer.",
        "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {
        "name": "focus_app",
        "description": "Bring a window to the foreground.",
        "parameters": {"type": "object",
                       "properties": {"name": {"type": "string"}},
                       "required": ["name"]}}},
    {"type": "function", "function": {
        "name": "launch_app",
        "description": "Launch a desktop app (notepad, calculator, vs code, chrome).",
        "parameters": {"type": "object",
                       "properties": {"name": {"type": "string"}},
                       "required": ["name"]}}},
    {"type": "function", "function": {
        "name": "read_screen",
        "description": "Read text visible on the user's screen (OCR). Use when asked what's on screen or to read an error.",
        "parameters": {"type": "object", "properties": {}}}},
    {"type": "function", "function": {
        "name": "win_click",
        "description": "Click a named button/control inside a window (native UI control, Code Mode gated).",
        "parameters": {"type": "object",
                       "properties": {"window": {"type": "string"},
                                      "control": {"type": "string"}},
                       "required": ["window", "control"]}}},
    {"type": "function", "function": {
        "name": "win_type",
        "description": "Type text into a named field inside a window (Code Mode gated).",
        "parameters": {"type": "object",
                       "properties": {"window": {"type": "string"},
                                      "control": {"type": "string"},
                                      "text": {"type": "string"}},
                       "required": ["window", "control", "text"]}}},
    {"type": "function", "function": {
        "name": "folder_watch",
        "description": "Watch a folder; JARVIS flags new files as they land.",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}},
                       "required": ["path"]}}},
    {"type": "function", "function": {
        "name": "folder_unwatch",
        "description": "Stop watching folders (one path, or all if empty).",
        "parameters": {"type": "object",
                       "properties": {"path": {"type": "string"}}}}},
    {"type": "function", "function": {
        "name": "computer_run",
        "description": "Run a computer task via Open Interpreter (writes code and runs it; asks approval for risky steps). Prefer small direct tools for one-liners.",
        "parameters": {"type": "object",
                       "properties": {"goal": {"type": "string"},
                                      "timeout": {"type": "integer"}},
                       "required": ["goal"]}}},
    {"type": "function", "function": {
        "name": "open_url",
        "description": "Open ANY url as a real tab in the user's browser (shortcuts, domains, or full links).",
        "parameters": {"type": "object",
                       "properties": {"url": {"type": "string"}},
                       "required": ["url"]}}},
]
